export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";

export const USER_lOGOUT_REQUEST = "USER_lOGOUT_REQUEST";
export const USER_lOGOUT_SUCCESS = "USER_lOGOUT_SUCCESS";
export const USER_lOGOUT_FAILURE = "USER_lOGOUT_FAILURE";

export const CLEAR_ERROR = "CLEAR_ERROR";
